name: budget_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # Stato applicazione
  provider: ^6.1.2

  # Database locale
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Grafici
  fl_chart: ^0.68.0

  # Import file
  file_picker: ^8.3.7

  # Lettura Excel
  excel: ^4.0.6

  # Lettura CSV
  csv: ^6.0.0

  # Chiamate API Gemini
  http: ^1.6.0

  # Icone iOS
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true